### ISSUE TITLE
No License File 

### ISSUE THREAD

**Issue by maxcapraro** [benlogan1981/VerticalSankey#3]
I really liked your implementation of a vertical sankey diagram. Unfortunately, the project does not have a license file and so I do not feel confident to reuse it.

Please consider deciding for a license (maybe APACHE 2.0 or MIT) to enable others including me to reuse your cool code :)

**Comment by benlogan1981** [comment]
Hey @maxcapraro - this has been done. MIT. Please go ahead and make use of this code - enjoy!

**Comment by maxcapraro** [comment]
Awesome @benlogan1981! Thanks a lot :)
